# Generated by Django 4.2.3 on 2023-08-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
