# Generated by Django 4.2.3 on 2023-08-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comp_is_startup',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='comp_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='comp_registered',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
