# Generated by Django 4.2.3 on 2023-10-27 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_activity_name_alter_category_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="viewedcompany",
            unique_together=set(),
        ),
    ]
