# Generated by Django 4.2.3 on 2023-11-07 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0002_alter_activity_name_alter_category_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="viewedcompany",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="viewedcompany",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
