# Generated by Django 4.2.3 on 2023-09-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_viewedcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='comp_region',
        ),
        migrations.AddField(
            model_name='profile',
            name='comp_region',
            field=models.ManyToManyField(to='profiles.region'),
        ),
    ]
