# Generated by Django 4.2.4 on 2023-12-21 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_logo_image_alter_profile_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='create_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='profile',
            name='update_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
