# Generated by Django 4.2.4 on 2023-12-21 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_logo_image_alter_profile_banner_image'),
    ]

    def add_created_at_updated_at_field(app, schema_editor):
        Profile = app.get_model("profiles", "Profile")
        for instance in Profile.objects.all():
            instance.created_at = datetime.date.today
            instance.updated_at = datetime.date.today

    operations = [
        migrations.RunPython(add_created_at_updated_at_field, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
