# Generated by Django 4.2.4 on 2024-01-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completeness',
            field=models.SmallIntegerField(default=0),
        ),
    ]
