# Generated by Django 4.2.3 on 2024-02-20 12:21

from django.db import migrations, models
import validation.validate_edrpou


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_remove_profile_edrpou_char_alter_profile_edrpou"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="edrpou",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=8,
                null=True,
                unique=True,
                validators=[validation.validate_edrpou.validate_edrpou],
            ),
        ),
    ]
