# Generated by Django 4.2.3 on 2024-02-22 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "profiles",
            "0010_alter_profile_address_alter_profile_banner_image_and_more",
        ),
        ("profiles", "0010_alter_profile_edrpou"),
    ]

    operations = []
