# Generated by Django 4.2.3 on 2024-03-23 15:49

from django.db import migrations, models
import validation.validate_rnokpp


class Migration(migrations.Migration):
    dependencies = [
        (
            "profiles",
            "0010_alter_profile_address_alter_profile_banner_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ipn",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=10,
                null=True,
                unique=True,
                validators=[validation.validate_rnokpp.validate_rnokpp],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_fop",
            field=models.BooleanField(default=False),
        ),
    ]
