# Generated by Django 4.2.3 on 2024-06-12 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import images.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileImage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "image_type",
                    models.CharField(
                        choices=[("banner", "banner"), ("logo", "logo")], max_length=10
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=5)),
                (
                    "image_path",
                    models.ImageField(
                        blank=True, upload_to=images.models.image_directory_path
                    ),
                ),
                ("image_size", models.PositiveIntegerField(null=True)),
                ("hash_md5", models.CharField(blank=True, max_length=32)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
