# Generated by Django 4.2.3 on 2024-06-18 14:38

import django.core.validators
from django.db import migrations, models
import images.models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileimage",
            name="image_path",
            field=models.ImageField(
                blank=True,
                upload_to=images.models.image_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpeg", "png", "jpg"]
                    )
                ],
            ),
        ),
    ]
