# Generated by Django 4.2.3 on 2023-08-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='comp_is_startup',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='comp_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='comp_registered',
        ),
    ]
