# Generated by Django 4.2.3 on 2024-07-03 08:51

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutoModeration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_moderation_hours",
                    models.PositiveSmallIntegerField(
                        default=12,
                        validators=[
                            administration.models.validate_auto_moderation_hours
                        ],
                    ),
                ),
            ],
        ),
    ]
