# Generated by Django 4.2.3 on 2024-02-19 21:31

import django.core.validators
from django.db import migrations, models
import validation.validate_edrpou
import validation.validate_image
import validation.validate_phone_number


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_remove_profile_edrpou_char_alter_profile_edrpou"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="banners",
                validators=[
                    validation.validate_image.validate_image_format,
                    validation.validate_image.validate_banner_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="common_info",
            field=models.TextField(
                blank=True,
                default="",
                validators=[django.core.validators.MaxLengthValidator(2000)],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="edrpou",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=8,
                null=True,
                unique=True,
                validators=[validation.validate_edrpou.validate_edrpou],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="logo_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="logos",
                validators=[
                    validation.validate_image.validate_image_format,
                    validation.validate_image.validate_logo_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="official_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="person_position",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=12,
                validators=[
                    validation.validate_phone_number.validate_phone_number_is_digit,
                    validation.validate_phone_number.validate_phone_number_len,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="product_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("Kyiv", "Київ"),
                    ("Vinnytsia region", "Вінницька область"),
                    ("Volyn region", "Волинська область"),
                    ("Dnipro region", "Дніпропетровська область"),
                    ("Donetsk region", "Донецька область"),
                    ("Zhytomyr region", "Житомирська область"),
                    ("Zakarpattia region", "Закарпатська область"),
                    ("Zaporizhzhia region", "Запорізька область"),
                    ("IvanoFrankivsk region", "Івано-Франківська область"),
                    ("Kyiv region", "Київська область"),
                    ("Kirovohrad region", "Кіровоградська область"),
                    ("Crimea", "Автономна Республіка Крим"),
                    ("Luhansk region", "Луганська область"),
                    ("Lviv region", "Львівська область"),
                    ("Mykolaiv region", "Миколаївська область"),
                    ("Odesa region", "Одеська область"),
                    ("Poltava region", "Полтавська область"),
                    ("Rivne region", "Рівненська область"),
                    ("Sevastopol", "Севастополь"),
                    ("Sumy region", "Сумська область"),
                    ("Ternopil region", "Тернопільська область"),
                    ("Kharkiv region", "Харківська область"),
                    ("Kherson region", "Херсонська область"),
                    ("Khmelnytskyi region", "Хмельницька область"),
                    ("Cherkasy region", "Черкаська область"),
                    ("Chernivtsi region", "Чернівецька область"),
                    ("Chernihiv region", "Чернігівська область"),
                ],
                default="",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="service_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="startup_idea",
            field=models.TextField(blank=True, default=""),
        ),
    ]
