# Generated by Django 4.2.3 on 2024-04-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_region_remove_profile_region_profile_regions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="regions",
            field=models.ManyToManyField(blank=True, to="profiles.region"),
        ),
    ]
