# Generated by Django 4.2.3 on 2024-06-11 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
        ("profiles", "0014_remove_profile_ipn_profile_rnokpp"),
    ]

    def move_image_fileds_to_profile_image_model(app, schema_editor):
        Profile = app.get_model("profiles", "Profile")
        ProfileImage = app.get_model("images", "ProfileImage")
        for instance in Profile.objects.all():
            if instance.banner_image and not instance.banner_approved:
                image_instance = ProfileImage.objects.create(
                    image_path=instance.banner_image,
                    image_type=ProfileImage.BANNER,
                    created_by=instance.person,
                    is_approved=True,
                )
                instance.banner_approved = image_instance
                instance.save()
            if instance.logo_image and not instance.logo_approved:
                image_instance = ProfileImage.objects.create(
                    image_path=instance.logo_image,
                    image_type=ProfileImage.LOGO,
                    created_by=instance.person,
                    is_approved=True,
                )
                instance.logo_approved = image_instance
                instance.save()

    def update_completeness_value(app, schema_editor):
            Profile = app.get_model("profiles", "Profile")
            Region = app.get_model("profiles", "Region")
            Activity = app.get_model("profiles", "Activity")
            Category = app.get_model("profiles", "Category")
            for instance in Profile.objects.all():
                instance.completeness = 0
                if instance.banner_approved:
                    instance.completeness += 100
                if instance.logo_approved:
                    instance.completeness += 1
                if Activity.objects.all().filter(profile=instance.id):
                    instance.completeness += 1
                if Category.objects.all().filter(profile=instance.id):
                    instance.completeness += 1
                if Region.objects.all().filter(profile=instance.id):
                    instance.completeness += 1
                instance.save()

    operations = [

        migrations.AddField(
            model_name="profile",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_banner",
                to="images.profileimage",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="banner_approved",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_banner_approved",
                to="images.profileimage",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logo_banner",
                to="images.profileimage",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="logo_approved",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_logo_approved",
                to="images.profileimage",
            ),
        ),
        migrations.RunPython(move_image_fileds_to_profile_image_model, migrations.RunPython.noop, elidable=True),
        migrations.RunPython(update_completeness_value, reverse_code=migrations.RunPython.noop, elidable=True),
        migrations.RemoveField(
            model_name="profile",
            name="banner_image",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="logo_image",
        ),
    ]
