# Generated by Django 4.2.3 on 2024-06-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
        ("profiles", "0014_remove_profile_ipn_profile_rnokpp"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_banner",
                to="images.profileimage",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="banner_approved",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_banner_approved",
                to="images.profileimage",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_logo",
                to="images.profileimage",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="logo_approved",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_logo_approved",
                to="images.profileimage",
            ),
        ),
    ]
