# Generated by Django 4.2.3 on 2024-06-14 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0016_move_images_update_completeness"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="banner_image",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="logo_image",
        ),
    ]
