# Generated by Django 4.2.3 on 2024-07-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0017_remove_profile_banner_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[
                    ("undefined", "Undefined"),
                    ("pending", "Pending Moderation"),
                    ("blocked", "Blocked"),
                    ("approved", "Approved"),
                    ("auto_approved", "Auto Approved"),
                ],
                default="undefined",
                max_length=15,
            ),
        ),
    ]
