# Generated by Django 4.2.3 on 2024-07-17 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0018_profile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
