# Generated by Django 4.2.3 on 2024-08-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0019_profile_status_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedcompany",
            name="is_updated",
            field=models.BooleanField(default=False),
        ),
    ]
