# Generated by Django 4.2.3 on 2024-08-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0019_profile_status_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="official_name",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
    ]
