# Generated by Django 4.2.3 on 2024-08-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0020_alter_profile_official_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedcompany",
            name="is_updated",
            field=models.BooleanField(default=False),
        ),
    ]
