# Generated by Django 4.2.3 on 2024-12-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0021_savedcompany_is_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(default=None, max_length=45, null=True),
        ),
    ]
