name: Nginx_Deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker compouse DOWN old containers
        run: docker compose -f docker-compose.nginx.yml down -v
      - name: Docker compouse UP new containers
        run: docker compose -f docker-compose.nginx.yml up -d --build
      - name: Clean up old docker resources
        run: |
          docker container prune -f
          docker image prune -f