name: Testing FE

on: pull_request

env:
  REACT_APP_BASE_API_URL: http://localhost:8000

jobs:
  build_and_test:
    name: Testing # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          cd FrontEnd
          npm install

      - name: Code Testing
        run: |
          cd FrontEnd
          npm test